spring:
  #  jackson:
  #    serialization:
  #      fail-on-empty-beans: false
  #  jackson:
  #    serialization:
  #      indent_output: true

  datasource:
    #    initialization-mode: always

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect


#  spring.main.web-environment=false
#  spring.main.banner-mode=off